#!/usr/bin/env python3
"""Sync .github/supported-boards.yml from test/emu/hardware_map.yml.

The hw-matrix dynamic_mode allocator reads .github/supported-boards.yml to
filter coordinator places by `tags.board`. To keep that list aligned with
the boards pyadi-iio actually has class wrappers for, this script extracts
every top-level entry in hardware_map.yml that declares
`pyadi_iio_class_support` and writes them out sorted/deduplicated.

Usage:
    python .github/scripts/sync-supported-boards.py          # regenerate
    python .github/scripts/sync-supported-boards.py --check  # exit non-zero on drift
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
HARDWARE_MAP = REPO_ROOT / "test" / "emu" / "hardware_map.yml"
SUPPORTED_BOARDS = REPO_ROOT / ".github" / "supported-boards.yml"

HEADER = (
    "# Generated by .github/scripts/sync-supported-boards.py. Do not edit by\n"
    "# hand — re-run the script to refresh from test/emu/hardware_map.yml.\n"
    "#\n"
    "# Consumed by the hw-matrix dynamic_mode allocator: each entry is matched\n"
    "# against the `board` tag of every coordinator place at preflight.\n"
)


def extract_boards(hw_map_path: Path) -> list[str]:
    doc = yaml.safe_load(hw_map_path.read_text()) or {}
    boards: set[str] = set()
    for name, entries in doc.items():
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if isinstance(entry, dict) and "pyadi_iio_class_support" in entry:
                boards.add(name)
                break
    return sorted(boards)


def render(boards: list[str]) -> str:
    lines = [HEADER, "boards:"]
    lines.extend(f"  - {b}" for b in boards)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if supported-boards.yml is out of date; do not write.",
    )
    args = parser.parse_args()

    boards = extract_boards(HARDWARE_MAP)
    new_content = render(boards)
    current = SUPPORTED_BOARDS.read_text() if SUPPORTED_BOARDS.exists() else ""

    if args.check:
        if current != new_content:
            print(
                f"{SUPPORTED_BOARDS.relative_to(REPO_ROOT)} is out of date. "
                "Re-run `python .github/scripts/sync-supported-boards.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    SUPPORTED_BOARDS.write_text(new_content)
    print(f"Wrote {len(boards)} boards to {SUPPORTED_BOARDS.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
