# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'realtimeEITUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmb_comm_select = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_comm_select.setGeometry(QtCore.QRect(10, 10, 351, 22))
        self.cmb_comm_select.setObjectName("cmb_comm_select")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setGeometry(QtCore.QRect(400, 10, 81, 23))
        self.btn_connect.setObjectName("btn_connect")
        self.grp_dataset = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_dataset.setGeometry(QtCore.QRect(10, 40, 91, 91))
        self.grp_dataset.setObjectName("grp_dataset")
        self.rbtn_real = QtWidgets.QRadioButton(self.grp_dataset)
        self.rbtn_real.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rbtn_real.setObjectName("rbtn_real")
        self.rbtn_imaginary = QtWidgets.QRadioButton(self.grp_dataset)
        self.rbtn_imaginary.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.rbtn_imaginary.setObjectName("rbtn_imaginary")
        self.rbtn_magnitude = QtWidgets.QRadioButton(self.grp_dataset)
        self.rbtn_magnitude.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.rbtn_magnitude.setObjectName("rbtn_magnitude")
        self.sldr_freq = QtWidgets.QSlider(self.centralwidget)
        self.sldr_freq.setGeometry(QtCore.QRect(380, 50, 91, 22))
        self.sldr_freq.setMinimum(10)
        self.sldr_freq.setMaximum(80)
        self.sldr_freq.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_freq.setObjectName("sldr_freq")
        self.sldr_p = QtWidgets.QSlider(self.centralwidget)
        self.sldr_p.setGeometry(QtCore.QRect(380, 80, 91, 22))
        self.sldr_p.setMinimum(1)
        self.sldr_p.setProperty("value", 50)
        self.sldr_p.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_p.setObjectName("sldr_p")
        self.sldr_lambda = QtWidgets.QSlider(self.centralwidget)
        self.sldr_lambda.setGeometry(QtCore.QRect(380, 110, 91, 22))
        self.sldr_lambda.setMinimum(1)
        self.sldr_lambda.setProperty("value", 50)
        self.sldr_lambda.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_lambda.setObjectName("sldr_lambda")
        self.sbox_p = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sbox_p.setGeometry(QtCore.QRect(480, 80, 51, 22))
        self.sbox_p.setMinimum(0.01)
        self.sbox_p.setMaximum(0.99)
        self.sbox_p.setSingleStep(0.01)
        self.sbox_p.setProperty("value", 0.5)
        self.sbox_p.setObjectName("sbox_p")
        self.sbox_lambda = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sbox_lambda.setGeometry(QtCore.QRect(480, 110, 51, 22))
        self.sbox_lambda.setMinimum(0.01)
        self.sbox_lambda.setMaximum(0.99)
        self.sbox_lambda.setSingleStep(0.01)
        self.sbox_lambda.setProperty("value", 0.5)
        self.sbox_lambda.setObjectName("sbox_lambda")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 50, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 80, 31, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 110, 41, 16))
        self.label_3.setObjectName("label_3")
        self.btn_baseline = QtWidgets.QPushButton(self.centralwidget)
        self.btn_baseline.setGeometry(QtCore.QRect(484, 10, 51, 23))
        self.btn_baseline.setObjectName("btn_baseline")
        self.sbox_freq = QtWidgets.QSpinBox(self.centralwidget)
        self.sbox_freq.setGeometry(QtCore.QRect(480, 50, 51, 22))
        self.sbox_freq.setMinimum(10)
        self.sbox_freq.setMaximum(80)
        self.sbox_freq.setObjectName("sbox_freq")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 140, 521, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout_plot = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout_plot.setContentsMargins(0, 0, 0, 0)
        self.vLayout_plot.setObjectName("vLayout_plot")
        self.btn_refresh_comm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_refresh_comm.setGeometry(QtCore.QRect(370, 10, 21, 21))
        self.btn_refresh_comm.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        self.btn_refresh_comm.setIcon(icon)
        self.btn_refresh_comm.setObjectName("btn_refresh_comm")
        self.grp_reconstruction = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_reconstruction.setGeometry(QtCore.QRect(110, 40, 91, 91))
        self.grp_reconstruction.setObjectName("grp_reconstruction")
        self.rbtn_bp = QtWidgets.QRadioButton(self.grp_reconstruction)
        self.rbtn_bp.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.rbtn_bp.setObjectName("rbtn_bp")
        self.rbtn_jac = QtWidgets.QRadioButton(self.grp_reconstruction)
        self.rbtn_jac.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.rbtn_jac.setObjectName("rbtn_jac")
        self.rbtn_greit = QtWidgets.QRadioButton(self.grp_reconstruction)
        self.rbtn_greit.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.rbtn_greit.setObjectName("rbtn_greit")
        self.grp_electro_num = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_electro_num.setGeometry(QtCore.QRect(210, 40, 71, 51))
        self.grp_electro_num.setObjectName("grp_electro_num")
        self.cmb_supported_electrode_count_select = QtWidgets.QComboBox(
            self.grp_electro_num
        )
        self.cmb_supported_electrode_count_select.setGeometry(
            QtCore.QRect(10, 20, 51, 22)
        )
        self.cmb_supported_electrode_count_select.setMaxVisibleItems(5)
        self.cmb_supported_electrode_count_select.setMaxCount(25)
        self.cmb_supported_electrode_count_select.setObjectName(
            "cmb_supported_electrode_count_select"
        )
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmb_supported_electrode_count_select.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Realtime EIT"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.grp_dataset.setTitle(_translate("MainWindow", "Dataset"))
        self.rbtn_real.setText(_translate("MainWindow", "Real"))
        self.rbtn_imaginary.setText(_translate("MainWindow", "Imaginary"))
        self.rbtn_magnitude.setText(_translate("MainWindow", "Magnitude"))
        self.label.setText(_translate("MainWindow", "Frequency (kHz)"))
        self.label_2.setText(_translate("MainWindow", "p"))
        self.label_3.setText(_translate("MainWindow", "lambda"))
        self.btn_baseline.setText(_translate("MainWindow", "Baseline"))
        self.grp_reconstruction.setTitle(_translate("MainWindow", "Reconstruction"))
        self.rbtn_bp.setText(_translate("MainWindow", "BP"))
        self.rbtn_jac.setText(_translate("MainWindow", "JAC"))
        self.rbtn_greit.setText(_translate("MainWindow", "GREIT"))
        self.grp_electro_num.setTitle(_translate("MainWindow", "Electrodes"))
